---
apiVersion: v1
kind: Service
metadata:
  name: demo2-service
  namespace: default
  labels:
    app: demo2-service
spec:
  ports:
    - port: 8101
      name: tcp
  selector:
    app: demo2-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2-service
  namespace: default
spec:
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  selector:
    matchLabels:
      app: demo2-service
  template:
    metadata:
      labels:
        app: demo2-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - demo2-service
              weight: 1
      containers:
        - name: demo2-service
          image: freemanliu/demo2-service:v1.0.1
          imagePullPolicy: Always
          lifecycle:
            preStop:
              httpGet:
                port: 8101
                path: /spring/shutdown
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8101
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8101
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 1Gi
          ports:
            - containerPort: 8101
          env:
            - name: EUREKA_SERVER
              value: "http://eureka-0.eureka:8761/eureka/,http://eureka-1.eureka:8761/eureka/,http://eureka-2.eureka:8761/eureka/"
            - name: SAMPLER_PROBABILITY
              value: "1.0"
            - name: ZIPKIN
              value: "http://10.96.0.13:9411/"
