server:
  undertow:
    worker-threads: 50
    io-threads: 2
  port: 8101
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/plain,application/x-javascript,text/css,application/xml
    min-response-size: 4096
spring:
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: ${SAMPLER_PROBABILITY:1.0}
  application:
    name: demo2-service
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  zipkin:
    base-url: ${ZIPKIN:http://10.96.0.13:9411/}



logging:
  logPath: /var/log/${spring.application.name}
  level:
    com.netflix.discovery.shared.resolver.aws: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
